import { NextResponse } from "next/server";

type ApiStandingsTeam = {
  team_id: number;
  team_name: string;
  team_image_url: string;
  played: number;
  won: number;
  drawn: number;
  lost: number;
  goals_for: number;
  goals_against: number;
  goal_difference: number;
  points: number;
  form: string[];
  rank: number;
  previous_rank: number;
};

type ApiStandingsGroup = {
  group_id: number;
  group_name: string;
  tournament_category_id: number;
  tournament_category_name: string;
  tournament_category_color: string;
  teams: ApiStandingsTeam[];
};

const standingsByTournamentId: Record<number, ApiStandingsGroup[]> = {
  110: [
    {
      group_id: 1,
      group_name: "A",
      tournament_category_id: 1101,
      tournament_category_name: "Putra",
      tournament_category_color: "#c01020",
      teams: [
        {
          team_id: 1,
          team_name: "DKI Jakarta",
          team_image_url: "",
          played: 3,
          won: 2,
          drawn: 1,
          lost: 0,
          goals_for: 7,
          goals_against: 3,
          goal_difference: 4,
          points: 7,
          form: ["W", "D", "W"],
          rank: 1,
          previous_rank: 2,
        },
        {
          team_id: 2,
          team_name: "Jawa Barat",
          team_image_url: "",
          played: 3,
          won: 2,
          drawn: 0,
          lost: 1,
          goals_for: 6,
          goals_against: 4,
          goal_difference: 2,
          points: 6,
          form: ["W", "W", "L"],
          rank: 2,
          previous_rank: 1,
        },
        {
          team_id: 3,
          team_name: "Jawa Tengah",
          team_image_url: "",
          played: 3,
          won: 0,
          drawn: 2,
          lost: 1,
          goals_for: 3,
          goals_against: 5,
          goal_difference: -2,
          points: 2,
          form: ["D", "L", "D"],
          rank: 3,
          previous_rank: 3,
        },
        {
          team_id: 4,
          team_name: "Jawa Timur",
          team_image_url: "",
          played: 3,
          won: 0,
          drawn: 1,
          lost: 2,
          goals_for: 2,
          goals_against: 6,
          goal_difference: -4,
          points: 1,
          form: ["L", "D", "L"],
          rank: 4,
          previous_rank: 4,
        },
      ],
    },
    {
      group_id: 2,
      group_name: "B",
      tournament_category_id: 1101,
      tournament_category_name: "Putra",
      tournament_category_color: "#c01020",
      teams: [
        {
          team_id: 5,
          team_name: "Sumatera Utara",
          team_image_url: "",
          played: 3,
          won: 2,
          drawn: 1,
          lost: 0,
          goals_for: 5,
          goals_against: 2,
          goal_difference: 3,
          points: 7,
          form: ["W", "D", "W"],
          rank: 1,
          previous_rank: 1,
        },
        {
          team_id: 6,
          team_name: "Sulawesi Selatan",
          team_image_url: "",
          played: 3,
          won: 2,
          drawn: 0,
          lost: 1,
          goals_for: 6,
          goals_against: 4,
          goal_difference: 2,
          points: 6,
          form: ["L", "W", "W"],
          rank: 2,
          previous_rank: 3,
        },
        {
          team_id: 7,
          team_name: "Banten",
          team_image_url: "",
          played: 3,
          won: 1,
          drawn: 0,
          lost: 2,
          goals_for: 4,
          goals_against: 6,
          goal_difference: -2,
          points: 3,
          form: ["W", "L", "L"],
          rank: 3,
          previous_rank: 2,
        },
        {
          team_id: 8,
          team_name: "DI Yogyakarta",
          team_image_url: "",
          played: 3,
          won: 0,
          drawn: 1,
          lost: 2,
          goals_for: 2,
          goals_against: 5,
          goal_difference: -3,
          points: 1,
          form: ["D", "L", "L"],
          rank: 4,
          previous_rank: 4,
        },
      ],
    },
  ],
  120: [
    {
      group_id: 3,
      group_name: "A",
      tournament_category_id: 1201,
      tournament_category_name: "Putri",
      tournament_category_color: "#0f2a5e",
      teams: [
        {
          team_id: 21,
          team_name: "Jawa Barat",
          team_image_url: "",
          played: 3,
          won: 2,
          drawn: 1,
          lost: 0,
          goals_for: 6,
          goals_against: 2,
          goal_difference: 4,
          points: 7,
          form: ["W", "D", "W"],
          rank: 1,
          previous_rank: 2,
        },
        {
          team_id: 22,
          team_name: "DKI Jakarta",
          team_image_url: "",
          played: 3,
          won: 2,
          drawn: 0,
          lost: 1,
          goals_for: 5,
          goals_against: 3,
          goal_difference: 2,
          points: 6,
          form: ["W", "W", "L"],
          rank: 2,
          previous_rank: 1,
        },
        {
          team_id: 23,
          team_name: "Jawa Timur",
          team_image_url: "",
          played: 3,
          won: 1,
          drawn: 0,
          lost: 2,
          goals_for: 3,
          goals_against: 4,
          goal_difference: -1,
          points: 3,
          form: ["L", "W", "L"],
          rank: 3,
          previous_rank: 3,
        },
        {
          team_id: 24,
          team_name: "Sulawesi Selatan",
          team_image_url: "",
          played: 3,
          won: 0,
          drawn: 1,
          lost: 2,
          goals_for: 2,
          goals_against: 7,
          goal_difference: -5,
          points: 1,
          form: ["D", "L", "L"],
          rank: 4,
          previous_rank: 4,
        },
      ],
    },
  ],
  130: [
    {
      group_id: 4,
      group_name: "A",
      tournament_category_id: 1301,
      tournament_category_name: "Junior",
      tournament_category_color: "#16a34a",
      teams: [
        {
          team_id: 31,
          team_name: "Banten",
          team_image_url: "",
          played: 2,
          won: 2,
          drawn: 0,
          lost: 0,
          goals_for: 4,
          goals_against: 1,
          goal_difference: 3,
          points: 6,
          form: ["W", "W"],
          rank: 1,
          previous_rank: 1,
        },
        {
          team_id: 32,
          team_name: "Jawa Tengah",
          team_image_url: "",
          played: 2,
          won: 1,
          drawn: 0,
          lost: 1,
          goals_for: 3,
          goals_against: 2,
          goal_difference: 1,
          points: 3,
          form: ["L", "W"],
          rank: 2,
          previous_rank: 3,
        },
        {
          team_id: 33,
          team_name: "DI Yogyakarta",
          team_image_url: "",
          played: 2,
          won: 1,
          drawn: 0,
          lost: 1,
          goals_for: 2,
          goals_against: 3,
          goal_difference: -1,
          points: 3,
          form: ["W", "L"],
          rank: 3,
          previous_rank: 2,
        },
        {
          team_id: 34,
          team_name: "Sumatera Utara",
          team_image_url: "",
          played: 2,
          won: 0,
          drawn: 0,
          lost: 2,
          goals_for: 1,
          goals_against: 4,
          goal_difference: -3,
          points: 0,
          form: ["L", "L"],
          rank: 4,
          previous_rank: 4,
        },
      ],
    },
  ],
};

export async function GET(request: Request) {
  const url = new URL(request.url);
  const tournamentIdParam = Number(url.searchParams.get("tournament_id") ?? "0");
  const tournamentId = Number.isFinite(tournamentIdParam) ? tournamentIdParam : 0;

  return NextResponse.json({
    status: { code: "OK" },
    data: standingsByTournamentId[tournamentId] ?? [],
    other: null,
  });
}
